name: test
channels:
  - defaults
  - conda-forge
dependencies:
    # Base depends
  - numpy>=1.12.0
  - nomkl
  - python
  - pint>=0.10.0
  - pydantic>=1.8.2
  - dataclasses  # only for py36 and only b/c default channel pydantic missing the conditional dep

    # Optional depends
  - msgpack-python
  - networkx>=2.4.0
  - nglview

    # Testing
  - pytest
  - pytest-cov
  - codecov
  - scipy  # tests an aspect of a helper fn not used by qcel functionality
  - jsonschema
