name: test
channels:
  - defaults
  - conda-forge
dependencies:
    # Base depends
  - numpy
  - nomkl
  - python
  - pint
  - pydantic>=0.20

    # Optional depends
  - networkx
  - py3dmol

    # Testing
  - pytest>=3.9.1
  - pytest-cov
  - codecov
  - scipy  # tests an aspect of a helper fn not used by qcel functionality
