name: test
channels:
  - default
dependencies:
    # Base depends
  - numpy
  - nomkl
  - python

    # Testing
  - pytest
  - pytest-cov

    # Pip depends
  - pip:
    - codecov
    - pint
    - deepdiff
