# Configure LGTM for this package

extraction:
  python:
    python_setup:
      version: 3
path_classifiers:
  library:
    - versioneer.py  # Set Versioneer.py to an external "library" (3rd party code)
    - devtools/*
  generated:
    - nist_data/*
    - qcelemental/_version.py
