name: qcelemental-docs
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3
    - numpy
    - pydantic
    - pint

    - sphinx
    - sphinx_rtd_theme
    - sphinx-automodapi
    - sphinx-autodoc-typehints
    - graphviz

    - pip:
      - git+git://github.com/MolSSI/qcarchive-sphinx-theme#egg=qcarchive_sphinx_theme
