name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg:
          - conda-env: minimal
            python-version: 3.6
            label: mindep
          - conda-env: base
            python-version: 3.6
            label: minpy
          - conda-env: base-cf
            python-version: "3.10"
            label: full
    env:
      PYVER: ${{ matrix.cfg.python-version }}
      CONDA_ENV: ${{ matrix.cfg.conda-env }}

    steps:
    - uses: actions/checkout@v1

    - name: Setup Information
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a
        conda --version

    - name: Create Environment
      shell: bash
      run: |
        eval "$(conda shell.bash hook)" && conda activate
        python devtools/scripts/create_conda_env.py -n=test -p=$PYVER devtools/conda-envs/$CONDA_ENV.yaml

    - name: Install
      shell: bash
      run: |
        eval "$(conda shell.bash hook)" && conda activate test
        python -m pip install . --no-deps

    - name: Environment Information
      shell: bash
      run: |
        eval "$(conda shell.bash hook)" && conda activate test
        conda list --show-channel-urls

    - name: PyTest
      shell: bash
      run: |
        eval "$(conda shell.bash hook)" && conda activate test
        pytest -rws -v --cov=qcelemental --color=yes --cov-report=xml qcelemental/

    - name: PyTest Validate
      shell: bash
      if: matrix.cfg.label == 'full'
      run: |
        eval "$(conda shell.bash hook)" && conda activate test
        pytest -rws -v --color=yes --validate qcelemental/

    - name: QCSchema Examples Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      if: matrix.cfg.label == 'full' && github.event_name == 'push' && github.repository == 'MolSSI/QCElemental' && ( startsWith( github.ref, 'refs/tags/' ) || github.ref == 'refs/heads/master' )
      with:
        branch: qcschema-examples
        folder: qcelemental/tests/qcschema_instances

    - name: CodeCov  
      uses: codecov/codecov-action@v1

  release_sphinx:
    needs: [build]
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - conda-env: docs-cf
            python-version: 3.8
            label: Sphinx
            runs-on: ubuntu-latest

    name: "🐍 ${{ matrix.cfg.python-version }} • ${{ matrix.cfg.label }}"
    runs-on: ${{ matrix.cfg.runs-on }}

    steps:
    - uses: actions/checkout@v2

    - name: Create Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        environment-file: devtools/conda-envs/${{ matrix.cfg.conda-env }}.yaml
        python-version: ${{ matrix.cfg.python-version }}
        auto-activate-base: false

    - name: Environment Information
      run: |
        conda info
        conda list --show-channel-urls
    - name: Build Documentation
      run: |
        python -m pip install . --no-deps
        cd docs
        make html
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      if: github.event_name == 'push' && github.repository == 'MolSSI/QCElemental' && ( startsWith( github.ref, 'refs/tags/' ) || github.ref == 'refs/heads/master' )
      with:
        branch: gh-pages
        folder: docs/build/html
