name: Compat

on:
  push:
    branches:
      - master
      - next2025
      - next2026
  pull_request:
    branches:
      - master
      - next2025
      - next2026
  schedule:
    - cron: "9 16 * * 1"

jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - label: Py-min
            runs-on: "ubuntu-latest"
            python-version: "3.10"
            pytest:

          - label: Py-313
            runs-on: "ubuntu-latest"
            python-version: "3.13"
            pytest:

    name: "🐍 ${{ matrix.cfg.python-version }} • ${{ matrix.cfg.label }} • ${{ matrix.runs-on }}"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write a Conda Env File
        run: |
            cat > compat.yaml <<EOF
            name: test
            channels:
              - conda-forge
            dependencies:
              # Build
              - setuptools
              - setuptools-scm
              # Core
              - python
              - pydantic
              - pint
              - numpy
              # Downstream to be tested
              - qcengine
              - qcmanybody
              - qcfractal
              - psi4=1.10
              - optking
              - geometric
              - dftd3-python
              - dftd4-python
              # Testing
              - pytest
              - pytest-xdist
              - zstandard
              - postgresql
              - qcarchivetesting
              # Testing CMS
              #- dummy1
              #- dummy2
            EOF
            if [[ "${{ matrix.cfg.label }}" == "Py-314" ]]; then
                sed -i "s;- psi4;#- psi4;g" compat.yaml
            fi
            # model sed for L/W
            #   sed -i "s;;;g" compat.yaml
            # model sed for M
            #   sed -E -i.bak "s;;;g" compat.yaml
            cat compat.yaml

      - name: Create Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          environment-file: compat.yaml
          python-version: ${{ matrix.cfg.python-version }}
          auto-activate-base: false
          show-channel-urls: true
          add-pip-as-python-dependency: true
          channels: conda-forge
          conda-remove-defaults: true


      - name: Special Config - checkout geomeTRIC for testing data
        uses: actions/checkout@v4
        with:
          repository: leeping/geomeTRIC
          path: geomeTRIC

      - name: Test geomeTRIC
        if: true
        id: geometric
        continue-on-error: true
        run: |
          rm -rf $CONDA_PREFIX/lib/python${{ matrix.cfg.python-version }}/site-packages/geometric/data/
          rm -rf $CONDA_PREFIX/lib/python${{ matrix.cfg.python-version }}/site-packages/examples
          ln -s $GITHUB_WORKSPACE/geomeTRIC/geometric/data $CONDA_PREFIX/lib/python${{ matrix.cfg.python-version }}/site-packages/geometric/data
          ln -s $GITHUB_WORKSPACE/geomeTRIC/examples $CONDA_PREFIX/lib/python${{ matrix.cfg.python-version }}/site-packages/examples
          sed -i "s;< 100;< 10;g" $CONDA_PREFIX/lib/python${{ matrix.cfg.python-version }}/site-packages/geometric/tests/test_irc.py
          pytest -rws -v --color=yes -n auto --durations 15 --pyargs geometric \
            -k "irc and not neb_service"
          # two dimension mismatch test failures

      - name: Fail job if any piece failed
        if: |
          steps.qcengine.outcome != 'success' ||
          steps.qcfractal.outcome != 'success' ||
          steps.qcmanybody.outcome != 'success' ||
          steps.dftd3.outcome != 'success' ||
          steps.dftd4.outcome != 'success' ||
          steps.psi4.outcome != 'success' ||
          steps.optking.outcome != 'success' ||
          steps.geometric.outcome != 'success'
        run: |
          echo "One or more steps failed:"
          echo "qcengine: ${{ steps.qcengine.outcome }}"
          echo "qcfractal: ${{ steps.qcfractal.outcome }}"
          echo "qcmanybody: ${{ steps.qcmanybody.outcome }}"
          echo "dftd3: ${{ steps.dftd3.outcome }}"
          echo "dftd4: ${{ steps.dftd4.outcome }}"
          echo "psi4: ${{ steps.psi4.outcome }}"
          echo "optking: ${{ steps.optking.outcome }}"
          echo "geometric: ${{ steps.geometric.outcome }}"
          exit 1
