name: Format

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install black
        run: pip install "black>=22.1.0,<23.0a0"
      - name: Check code formatting with black
        run: black --check .

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install poetry
        run: pip install poetry
      - name: Install repo
        run: poetry install --no-interaction --no-ansi
      - name: Check import formatting with isort
        run: poetry run isort --check-only --diff .
# TODO: Support flake8 when the repo is ready :)
# flake8:
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: "3.7"
#     - name: Install flake8
#       run: pip install flake8
#     - name: Flake8
#       run: flake8 --count .

# TODO: Support mypy when the repo is ready
# mypy:
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: "3.8"
#     - name: Install repo
#       run: pip install -e '.[lint]'
#     - name: mypy
#       run: mypy .
