name: Format

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1

    - name: Python Setup
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create Environment
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install black

    - name: Lint
      shell: bash
      run: black qcelemental --check

