name: QCSchema

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        conda-env: [base]
        python-version: [3.7]
    env:
      PYVER: ${{ matrix.python-version }}
      CONDA_ENV: ${{ matrix.conda-env }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: qcel

    - name: Checkout schema repo
      uses: actions/checkout@v2
      with:
        repository: loriab/QCSchema
        #repository: MolSSI/QCSchema
        path: qcsk
        ref: py2json
        #ref: master

    - name: Python Setup
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create Environment
      shell: bash
      working-directory: ./qcel
      run: |
        eval "$(conda shell.bash hook)" && conda activate
        python devtools/scripts/create_conda_env.py -n=test -p=$PYVER devtools/conda-envs/$CONDA_ENV.yaml

    - name: Install
      shell: bash
      working-directory: ./qcel
      run: |
        eval "$(conda shell.bash hook)" && conda activate test
        python -m pip install . --no-deps

    - name: Environment Information
      shell: bash
      run: |
        eval "$(conda shell.bash hook)" && conda activate test
        conda list --show-channel-urls

    - name: QCSchema from QCElemental
      shell: bash
      working-directory: ./qcel
      run: |
        eval "$(conda shell.bash hook)" && conda activate test
        make qcschema
        ls -l qcschema
        cp -p qcschema/* ../qcsk/qcschema_json/
        # Note: `qcschema_json` is a folder in the py2json branch containing plain JSON files of the schema,
        #       rather than the python module of the current repo

    - name: ASDF
      shell: bash
      working-directory: ./qcsk
      run: |
        git diff --color-words
        pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        echo ${pull_number}
        branch=qcel-${pull_number}
        echo ${branch}
        git checkout -b ${branch}
        git remote -v
        git config --global user.email "lori.burns@gmail.com"
        git config --global user.name "Lori A. Burns"
        git add -A
        git commit -m "auto-generated from QCElemental"
        git push origin ${branch}

#    - name: CodeCov  
#      uses: codecov/codecov-action@v1
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        file: ./coverage.xml
#        flags: unittests
#        yml: ./.codecov.yml 
#

#####
#   pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
#####
